### ISSUE TITLE
Add a screen option

### ISSUE THREAD

**Issue by DrEggyniks91** [overbound/SonicTimeTwisted2.0#45]
Implement a screen size of 4:3 and 16:9. That way players can either enjoy the natural Sega Cd look or the widescreen variety.

**Comment by BlueSpeedsterYT** [comment]
while something that could work, it would definitely require a partial rewrite of the games code to account for multiple resolutions, I feel like having a global width variable that the game can recognize and change accordingly would be useful to prevent any potential hardcoded resolutions, how well it's implemented depends on the game's codebase being able to handle it.

**Comment by BlueSpeedsterYT** [comment]
https://github.com/overbound/SonicTimeTwisted2.0/assets/36098277/ed6a18e6-94ec-40f1-ad51-299b3586178f

as of today, the basic systems for a 4:3 mode have now been partially complete.
There are some additional issues to fix such as certain game aspects only expecting a widescreen resolution rather than a 4:3 one, those are planned to be fixed as more progress on the aspect ratio mode is done.
